<!doctype html>
<html lang="pt-br">
  <head>
    <title>Animes</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
      <link rel="stylesheet" href="../node_modules/bootstrap-icons/font/bootstrap-icons.css">
      <link rel="stylesheet" href="node_modules/bootstrap-icons/font/bootstrap-icons.css">
    <link href="../css/tema.css" rel="stylesheet" >
  </head>
<body>
  <?php include "../nav.php"?>
      <main>
        <h1 class="cor-letra"> ANIMES </h1>
        <article> <h2> Boruto </h2>   <a href="https://www.crunchyroll.com/pt-br/series/GR75Q020Y/boruto-naruto-next-generations"><figure><figcaption> <img src=" imgcosplay/boruto.png" alt=" Uzumaki Boruto, filho de Uzumaki Naruto, o Sétimo Hokage, se inscreveu na Academia Ninja para aprender a ser um verdadeiro ninja. Os outros estudantes o ignoram por ser apenas o filho do Hokage mas a paixão e a personalidade do Boruto vai acabar com todos esses preconceitos.Quando uma série de misteriosos eventos começa a se desenrolar, cabe a Boruto e seus novos amigos a investigá-los. Como um tornado, Boruto entra no coração de todos: sua história está prestes a começar!"> </a>  </figcaption></figure></article> 

        <article> <h2> My Hero Academy </h2>  <a href="https://www.crunchyroll.com/pt-br/series/G6NQ5DWZ6/my-hero-academia"><figure><figcaption><img src=" imgcosplay/myhero.png" alt="Por toda a sua vida, Izuku sonhou ser um heroi — um objetivo ambicioso para qualquer um, mas especialmente desafiador para um garoto sem superpoderes. Isso mesmo: em um mundo onde 80% da população tem algum tipo de Dom especial, Izuku teve a má sorte de nascer completamente normal. Mas isso não vai impedi-lo de se matricular em uma das academias de herois mais prestigiosas do mundo."></a>  </figcaption></figure></article> 

        <article> <h2> Dragon Ball Super </h2> <a href="https://www.crunchyroll.com/pt-br/series/GR19V7816/dragon-ball-super"><figure><figcaption><img src=" imgcosplay/dragonballsuper.png" alt="18 anos depois, temos uma nova saga de Dragon Ball das mãos de seu criador, Akira Toriyama. Após a derrota de Majin Buu, Goku arranja um novo emprego como... fazendeiro de nabos? Agora que a Terra está em paz, nosso heróis levam vidas mundanas, mas não por muito tempo.Longe dali, Beerus, o poderoso Deus da Destruição, recebe uma profecia de que encontrará seu fim nas mãos de um ser ainda mais poderoso, e sua busca pelo Deus dos Saiya-jins o traz para a Terra. Será que Goku e seus amigos conseguirão derrotar seu mais poderoso inimigo até então?"></a> <figcaption></figure></article> 

        <article> <h2> Hunter X Hunter </h2> <a href="https://www.crunchyroll.com/pt-br/series/GY3VKX1MR/hunter-x-hunter"><figure><figcaption><img src="imgcosplay/jujutsukaisen.png" alt="Monstros amedrontadores, criaturas exóticas, riquezas vastas, tesouros misteriosos, terras vis e terras inexploradas... Gon parte em uma aventura para se tornar um caçador profissional que arrisca a própria vida em busca do desconhecido. Pelo caminho, ele conhece outros participantes da Prova dos Caçadores: Kurapika, Leorio e Killua. Será Gon capaz de vencer os grandes desafios da Prova de Caçadores e se tornar o melhor do mundo? Esta jornada selvagem e épica está prestes a começar!!"> </a> </figcaption></figure></article> 

        <article> <h2> Demons Slayer </h2> <a href="https://www.crunchyroll.com/pt-br/series/GY5P48XEY/demon-slayer-kimetsu-no-yaib"> <img src=" imgcosplay/demonslayer.png" alt="Japão, era Taisho. Tanjiro, um bondoso jovem que ganha a vida vendendo carvão, descobre que sua família foi massacrada por um demônio. E pra piorar, Nezuko, sua irmã mais nova e única sobrevivente, também foi transformada num demônio. Arrasado com esta sombria realidade, Tanjiro decide se tornar um matador de demônios para fazer sua irmã voltar a ser humana, e para matar o demônio que matou sua família. Um triste conto sobre dois irmãos, onde os destinos dos humanos e dos demônios se entrelaçam, começa agora."></a>  </figcaption></figure></article> 

        <article> <h2> Jujutsu Kaisen </h2> <a href="https://www.crunchyroll.com/pt-br/series/GRDV0019R/jujutsu-kaisen"> <figure><figcaption><img src=" imgcosplay/jujutsukaisen.png" alt="Sofrimento, arrependimento, vergonha: os sentimentos negativos dos humanos tornam-se Maldições, causando terríveis acidentes que podem levar até mesmo à morte. E pra piorar, Maldições só podem ser exorcizadas por outras Maldições. Certo dia, para salvar amigos que estavam sendo atacados por Maldições, Yuji Itadori engole o dedo do Ryomen-Sukuna, absorvendo sua Maldição. Ele então decide se matricular no Colégio Técnico de Feitiçaria de Tóquio, uma organização que combate as Maldições... e assim começa a heróica lenda do garoto que tornou-se uma Maldição para exorcizar uma Maldição."> </a> </figcaption></figure></article> 

        <article> <h2> One Punch man </h2> <a href="https://www.crunchyroll.com/pt-br/series/G63K98PZ6/one-punch-man"> <figure><figcaption><img src=" imgcosplay/onepunchman.png" alt="Saitama é um cara que virou herói por diversão. Depois de realizar um *treino especial* por três anos, ele ficou tão poderoso que consegue derrotar qualquer oponente com um único soco. Agora, ao lado de Genos, seu fiel discípulo ciborgue, Saitama está pronto para encarar seus deveres como herói profissional da Associação de Heróis. Contudo, monstros têm aparecido com frequência cada vez maior, o que confirma as profecias da Grande Vidente Madame Shibabawa sobre o fim da Terra. E em meio a toda essa crise, surge Garou, o *caçador* de herois."> </a>  </figcaption></figure></article> 

        <article> <h2> Tokyo Revengers </h2> <a href="https://www.crunchyroll.com/pt-br/series/G3KHEVMN1/tokyo-revengers"> <figure><figcaption><img src=" imgcosplay/tokyorevengers.png" alt="Takemichi Hanagaki é um desempregado que sobrevive de bicos e está na fossa. Ele descobriu que Hinata Tachibana, sua primeira e última namorada, com quem namorou no fundamental, foi morta pela impiedosa Gangue Manji de Tóquio. No dia seguinte à notícia, ele está na beira da plataforma do trem e é empurrado pela multidão. Ele fecha os olhos se preparando para morrer, mas ao abrir, ele voltou no tempo para quando tinha 12 anos de idade. Agora que ele está na melhor época de sua vida, Takemichi decide se vingar de sua vida, salvando sua namorada e parando de fugir de si mesmo."> </a>  </figcaption></figure></article> 

        <article> <h2> Bleach </h2> <a href="https://www.crunchyroll.com/pt-br/series/GG5H5XK80/bleach-international-dubs"> <figure><figcaption><img src=" imgcosplay/bleach.png" alt="O jovem Ichigo é surpreendido com indesejadas habilidades de ceifeiro de almas e quer devolver os poderes. Mas deve executar algumas tarefas antes."> </figcaption></figure> </article>
      </main>
  <?php include "../rodape.php"?>
</body>
</html>